---
# Changes here will be overwritten by Copier
_commit: v2.58.0-3-g44f630c
_src_path: gh:remerge/template
project_id: ansible-role-dell
project_license: apache-2.0
project_name: Ansible Role for Dell
project_owner: core
project_type: ansible-role
use_python: true
use_ruby: false
